### ISSUE TITLE
编译正常但是浏览器无法访问页面

### ISSUE THREAD

**Issue by imic** [myems/myems-web#1]
myems-web 编译后复制到nginx后浏览器打开空白页面

` npm run build

> myems@1.0.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  439.77 KB  build/static/js/7.f816cd42.chunk.js
  178.91 KB  build/static/js/8.97643fca.chunk.js
  83.19 KB   build/static/js/9.3f714bdc.chunk.js
  71.98 KB   build/static/js/main.002fb31e.chunk.js
  61.53 KB   build/static/js/13.687096e7.chunk.js
  38.89 KB   build/static/js/11.2ad11164.chunk.js
  23.68 KB   build/static/js/2.dcbe4f9e.chunk.js
  22.19 KB   build/static/js/16.089692c1.chunk.js
  15.25 KB   build/static/js/10.4f1483e3.chunk.js
  14.64 KB   build/static/js/3.e7476dec.chunk.js
  12.95 KB   build/static/js/15.f08c37b4.chunk.js
  12.52 KB   build/static/js/14.d5a21b29.chunk.js
  12.4 KB    build/static/js/12.05b514b7.chunk.js
  8.5 KB     build/static/js/4.5f5222d2.chunk.js
  4.89 KB    build/static/css/10.bf0413c3.chunk.css
  4.16 KB    build/static/css/7.63d6a347.chunk.css
  1.64 KB    build/static/js/runtime-main.364ad635.js
  815 B      build/static/js/0.c20a6783.chunk.js
  475 B      build/static/js/17.487379a9.chunk.js
  473 B      build/static/js/1.c30117f0.chunk.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

`

**Comment by guangyuzhang** [comment]
正常运行至少还需要安装myems-api和数据库

**Comment by imic** [comment]
嗯，api运行了，数据库也没问题 myems-admin也正常访问
`sudo gunicorn -b 127.0.0.1:8080 app:api
[2020-10-27 22:53:12 -0400] [17658] [INFO] Starting gunicorn 20.0.4
[2020-10-27 22:53:12 -0400] [17658] [INFO] Listening at: http://127.0.0.1:8080 (17658)
[2020-10-27 22:53:12 -0400] [17658] [INFO] Using worker: sync
[2020-10-27 22:53:12 -0400] [17661] [INFO] Booting worker with pid: 17661
`

**Comment by guangyuzhang** [comment]
需要检查一下nginx.conf

**Comment by imic** [comment]
nginx.conf用的默认配置 readme上没有提到nginx.conf的配置信息

**Comment by guangyuzhang** [comment]
$ sudo mkdir /var/www
  $ sudo mkdir /var/www/html
  $ sudo mkdir /var/www/html/web
  $ sudo mkdir /var/www/html/admin
  $ sudo nano /etc/nginx/nginx.conf


  -- In the 'http' section, add a key value:

http{
    client_header_timeout 600;
    ...
    ...

}


-- Modify the default value in "http | server | location /' for myems-web as below:

location / {
    root   /var/www/html/web;
    index  index.html index.htm;
}

-- Add another location /api in 'http | server ' to proxy requests to myems-api, replace the example address http://127.0.0.1:8000/ with actual address  of myems-api:
location /api {
    proxy_pass http://127.0.0.1:8000/;
    proxy_connect_timeout 75;
    proxy_read_timeout 600;
    send_timeout 600;
}

-- Outside the first and default 'http|server' section, add another 'server' section for myems-admin as below:
http {
    ...
    ...
    server {
        ...
        ...
    }
    # add new server here
    server {

    }
}

-- Inside the new 'server' section, add values as below:
    ```
server {
        listen                 8001;
        server_name     myems-admin;
        location / {
            root    /var/www/html/admin;
            index index.html index.htm;
        }
        -- to avoid CORS issue, use Nginx to proxy myems-api to path /api with the same ip and port as myems-web
        -- Add another location /api in 'server ' to proxy requests to myems-api, replace the example address http://127.0.0.1:8000/ with actual address  of myems-api:
        location /api {
            proxy_pass http://127.0.0.1:8000/;
            proxy_connect_timeout 75;
            proxy_read_timeout 600;
            send_timeout 600;
        }
    }
```

**Comment by imic** [comment]
可以了 谢谢 ！
另外你们的网站似乎打不开https://myems.io/ 
如果需要商业授权怎么咨询
